### ISSUE TITLE
Will this be official site for siris?

### ISSUE THREAD

**Issue by chekun** [go-siris/siris-docs#1]
Hi, I am big fan of iris, so very happy to see you guys take over.

I'd like to translate this to Chinese when this is done.

And `go-siris.cn` is ready to serve the purpose. 😃

**Comment by Dexus** [comment]
Hi Che Kun,
yes it should be our website, but we have no release yet. Please stay tuned. I will trigger here again when its done.

Von meinem iPhone gesendet

**Comment by Dexus** [comment]
@chekun for which language `zh-cn` will you able to translate?

**Comment by chekun** [comment]
@Dexus `Simplified Chinese`
